export type ProductCategory =
  | "Laptops"
  | "Phones"
  | "Accessories"
  | "Networking"
  | "Monitors"
  | "Storage";

export type Brand = "HP" | "Dell" | "Lenovo" | "Apple" | "ASUS" | "Acer" | "TP-Link";

export type Product = {
  id: string;
  slug: string;
  name: string;
  category: ProductCategory;
  brand: Brand;
  priceGhs: number;
  rating: number; // 0-5
  inStock: boolean;
  shortDescription: string;
  description: string;
  highlights: string[];
  specs: Array<{ label: string; value: string }>;
  images: Array<{ src: string; alt: string }>;
};

export const brands: Brand[] = ["HP", "Dell", "Lenovo", "Apple", "ASUS", "Acer", "TP-Link"];

export const categories: ProductCategory[] = [
  "Laptops",
  "Phones",
  "Accessories",
  "Networking",
  "Monitors",
  "Storage",
];

export const products: Product[] = [
  {
    id: "p_dell_5440_i5_13th_16_512",
    slug: "dell-latitude-5440-i5-13th-16gb-512gb",
    name: "Dell Latitude 5440 (i5 13th Gen, 16GB, 512GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 12500,
    rating: 4.8,
    inStock: true,
    shortDescription:
      "Modern Latitude with strong performance, Iris Xe graphics, and premium security options.",
    description:
      "A business-class Dell Latitude built for fast everyday work. Great for office productivity, school, and multitasking—with a solid port selection and modern security features.",
    highlights: [
      "Intel Core i5 (13th Gen)",
      "16GB RAM",
      "512GB SSD storage",
      "Intel Iris Xe graphics",
      "Backlit keyboard",
      "Face ID + fingerprint",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (13th Gen, 12 CPUs)" },
      { label: "Speed", value: "Base 1.6GHz · Turbo up to 4.70GHz" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Graphics", value: "Intel Iris Xe" },
      { label: "Display", value: "14-inch" },
      { label: "Security", value: "Face ID, fingerprint" },
      { label: "Connectivity", value: "Wi‑Fi" },
      { label: "Ports", value: "USB‑C, HDMI, Ethernet" },
      { label: "Extras", value: "SIM slot" },
      { label: "Form factor", value: "180° hinge / convertible" },
    ],
    images: [{ src: "/products/laptop-dell-5440.png", alt: "Dell Latitude 5440" }],
  },
  {
    id: "p_hp_840_g5g6_i5_8th_8_256",
    slug: "hp-elitebook-840-g5-g6-i5-8th-8gb-256gb",
    name: "HP EliteBook 840 G5/G6 (i5 8th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 3990,
    rating: 4.6,
    inStock: true,
    shortDescription:
      "Clean EliteBook with backlit keyboard and biometric login for office and school work.",
    description:
      "A reliable HP EliteBook built for everyday productivity. Balanced performance, business-grade build quality, and useful ports for meetings and presentations.",
    highlights: [
      "Intel Core i5 (8th Gen)",
      "8GB RAM",
      "256GB SSD",
      "14-inch display",
      "Face ID recognition",
      "Fingerprint scanner + backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (8th Gen)" },
      { label: "Cores / Threads", value: "4 cores · 8 processors" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: "14-inch" },
      { label: "Security", value: "Face ID, fingerprint" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Camera", value: "Webcam" },
      { label: "Ports", value: "HDMI, USB‑C, Ethernet" },
    ],
    images: [{ src: "/products/laptop-hp-840.png", alt: "HP EliteBook 840" }],
  },
  {
    id: "p_lenovo_l390_i5_8th_8_256",
    slug: "lenovo-thinkpad-l390-i5-8th-8gb-256gb",
    name: "Lenovo ThinkPad L390 (i5 8th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "Lenovo",
    priceGhs: 3500,
    rating: 4.6,
    inStock: true,
    shortDescription:
      "Compact ThinkPad with solid ports and classic Lenovo reliability for work and school.",
    description:
      "A portable ThinkPad that’s easy to carry and dependable for everyday tasks. Great for students, remote work, and office productivity.",
    highlights: [
      "Intel Core i5 (8th Gen, 8 CPUs)",
      "8GB RAM",
      "256GB SSD storage",
      "13-inch display",
      "USB‑C + HDMI",
      "SD card slot",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (8th Gen, 8 CPUs)" },
      { label: "Speed", value: "Base ~1.8GHz · Turbo up to 3.90GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: "13-inch" },
      { label: "Camera", value: "Webcam" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "USB‑C, USB, HDMI, SD card slot" },
    ],
    images: [{ src: "/products/laptop-lenovo-t14.png", alt: "Lenovo ThinkPad L390" }],
  },
  {
    id: "p_dell_5320_i5_11th_16_256",
    slug: "dell-latitude-5320-i5-11th-16gb-256gb",
    name: "Dell Latitude 5320 (i5 11th Gen, 16GB, 256GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 5550,
    rating: 4.7,
    inStock: true,
    shortDescription:
      "Powerful 13.3-inch Latitude with 16GB RAM for smooth multitasking and business use.",
    description:
      "A compact Dell Latitude that’s fast and responsive for office work, browsing, and video calls. A great choice if you want 16GB RAM in a portable size.",
    highlights: [
      "Intel Core i5 (11th Gen)",
      "16GB RAM",
      "256GB SSD storage",
      "13.3-inch display",
      "Backlit keyboard",
      "Camera + Intel graphics",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (11th Gen)" },
      { label: "Speed", value: "Min 2.6GHz · Max 4.4GHz" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '13.3"' },
      { label: "Graphics", value: "Intel Graphics" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Camera", value: "Yes" },
      { label: "Color", value: "Gray" },
    ],
    images: [{ src: "/products/laptop-dell-latitude.png", alt: "Dell Latitude 5320" }],
  },
  {
    id: "p_hp_1030_g4_i5_8th_8_256",
    slug: "hp-elitebook-x360-1030-g4-i5-8th-8gb-256gb",
    name: "HP EliteBook x360 1030 G4 (i5 8th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 5900,
    rating: 4.7,
    inStock: true,
    shortDescription:
      "Premium x360 touchscreen EliteBook with sleek design, backlit keyboard, and facial recognition.",
    description:
      "A high-end convertible EliteBook with a crisp display and touchscreen flexibility. Ideal for meetings, presentations, note-taking, and travel.",
    highlights: [
      "Intel Core i5 (8th Gen)",
      "8GB RAM",
      "256GB SSD",
      "13.3-inch FHD IPS touchscreen",
      "x360 convertible",
      "Face ID + backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (8th Gen)" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '13.3" FHD IPS' },
      { label: "Touch", value: "Yes" },
      { label: "Form factor", value: "x360 convertible" },
      { label: "Security", value: "Facial ID recognition" },
      { label: "Keyboard", value: "Backlit" },
    ],
    images: [{ src: "/products/laptop-hp-360.png", alt: "HP EliteBook x360 1030 G4" }],
  },
  {
    id: "p_hp_830_g5_i5_8th_8_256",
    slug: "hp-elitebook-830-g5-i5-8th-8gb-256gb",
    name: "HP EliteBook 830 G5 (i5 8th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 4500,
    rating: 4.6,
    inStock: true,
    shortDescription:
      "Compact 13-inch EliteBook with backlit keyboard and fingerprint security for daily productivity.",
    description:
      "A portable EliteBook that’s ideal for work on the go. Reliable performance for office apps, browsing, and online meetings.",
    highlights: [
      "Intel Core i5 (8th Gen, 8 CPUs)",
      "8GB RAM",
      "256GB SSD storage",
      "13-inch display",
      "Fingerprint sensor",
      "Backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (8th Gen, 8 CPUs)" },
      { label: "Speed", value: "Base ~1.9GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: "13-inch" },
      { label: "Security", value: "Fingerprint sensor" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "USB‑C, USB, HDMI, Ethernet" },
    ],
    images: [{ src: "/products/laptop-hp-840.png", alt: "HP EliteBook 830 G5" }],
  },
  {
    id: "p_lenovo_t460_i5_6th_8_256_batch10",
    slug: "lenovo-thinkpad-t460-i5-6th-8gb-256gb",
    name: "Lenovo ThinkPad T460 (i5 6th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "Lenovo",
    priceGhs: 2800,
    rating: 4.5,
    inStock: true,
    shortDescription:
      "Affordable ThinkPad workhorse with double battery, backlit keyboard, and fingerprint login.",
    description:
      "A dependable, budget-friendly ThinkPad known for durability and keyboard comfort. Great for office work, school, and everyday tasks. Batch availability: 10pcs.",
    highlights: [
      "Intel Core i5 (6th Gen, 4 CPUs)",
      "8GB RAM",
      "256GB SSD storage",
      "14-inch display",
      "Double battery + fingerprint",
      "Backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (6th Gen, 4 CPUs)" },
      { label: "Speed", value: "Base 2.5GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: "14-inch" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Security", value: "Fingerprint reader" },
      { label: "Battery", value: "Double battery" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "USB, HDMI, Ethernet" },
      { label: "Camera", value: "Webcam" },
    ],
    images: [{ src: "/products/laptop-lenovo-t460.png", alt: "Lenovo ThinkPad T460" }],
  },
  {
    id: "p_dell_e5470_touch_i5_6th_8_256",
    slug: "dell-latitude-e5470-touch-i5-6th-8gb-256gb",
    name: "Dell Latitude E5470 Touch (i5 6th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 3900,
    rating: 4.5,
    inStock: true,
    shortDescription:
      "Touchscreen Latitude with 180° hinge and great ports for work, school, and presentations.",
    description:
      "A versatile Dell Latitude with touchscreen and a flexible hinge. Strong everyday performance for productivity, meetings, and browsing.",
    highlights: [
      "Intel Core i5 (6th Gen, 4 CPUs)",
      "8GB RAM",
      "256GB SSD storage",
      "14-inch touchscreen",
      "180° hinge / convertible",
      "Backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (6th Gen, 4 CPUs)" },
      { label: "Speed", value: "Base 2.5GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '14" touchscreen' },
      { label: "Form factor", value: "180° hinge / convertible" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "HDMI, USB, SD card slot" },
      { label: "Camera", value: "Webcam" },
    ],
    images: [{ src: "/products/laptop-dell-540.png", alt: "Dell Latitude E5470" }],
  },
  {
    id: "p_dell_e5470_touch_i5_6th_16_512",
    slug: "dell-latitude-e5470-touch-i5-6th-16gb-512gb",
    name: "Dell Latitude E5470 Touch (i5 6th Gen, 16GB, 512GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 4200,
    rating: 4.6,
    inStock: true,
    shortDescription:
      "Upgraded E5470 touchscreen with 16GB RAM and 512GB SSD for smoother multitasking.",
    description:
      "Same versatile Latitude E5470 touchscreen experience, upgraded for heavier multitasking and more storage—ideal for business workloads and multiple apps.",
    highlights: [
      "Intel Core i5 (6th Gen, 4 CPUs)",
      "16GB RAM",
      "512GB SSD storage",
      "14-inch touchscreen",
      "180° hinge / convertible",
      "Backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (6th Gen, 4 CPUs)" },
      { label: "Speed", value: "Base 2.5GHz" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '14" touchscreen' },
      { label: "Form factor", value: "180° hinge / convertible" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "HDMI, USB, SD card slot" },
      { label: "Camera", value: "Webcam" },
    ],
    images: [{ src: "/products/laptop-dell-540.png", alt: "Dell Latitude E5470" }],
  },
  {
    id: "p_dell_7400_i7_8th_16_512_touch",
    slug: "dell-latitude-7400-i7-8th-16gb-512gb-touch",
    name: "Dell Latitude 7400 (i7 8th Gen, 16GB, 512GB SSD, Touch)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 5700,
    rating: 4.7,
    inStock: true,
    shortDescription:
      "Executive Latitude with touchscreen, Windows 11 Pro, and premium security features.",
    description:
      "A powerful Latitude built for professionals who want performance, portability, and security. Great for office work, travel, and multitasking with plenty of RAM and fast SSD storage.",
    highlights: [
      "Intel Core i7 (8th Gen, 4 cores / 8 processors)",
      "16GB RAM",
      "512GB SSD storage",
      "14-inch FHD display + touchscreen",
      "Face ID + fingerprint",
      "Backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i7-8665U (8th Gen)" },
      { label: "Speed", value: "Base 1.90GHz · Turbo up to 4.8GHz" },
      { label: "Cores / Threads", value: "4 cores · 8 processors" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '14" FHD' },
      { label: "Touch", value: "Yes" },
      { label: "Security", value: "Face ID recognition, fingerprint sensor" },
      { label: "Keyboard", value: "Backlit" },
      { label: "OS", value: "Windows 11 Pro (English)" },
      { label: "Audio", value: "Stereo speakers (Realtek ALC3254)" },
    ],
    images: [{ src: "/products/laptop-dell-latitude.png", alt: "Dell Latitude 7400" }],
  },
  {
    id: "p_dell_7320_i5_11th_16_256_openbox",
    slug: "dell-latitude-7320-i5-11th-16gb-256gb-open-box",
    name: "Dell Latitude 7320 (i5 vPro 11th Gen, 16GB, 256GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 4900,
    rating: 4.7,
    inStock: true,
    shortDescription:
      "Open-box 13.3-inch Latitude with Iris Xe graphics, modern ports, and Windows 11 Pro compatibility.",
    description:
      "Brand new in open box. A premium compact Latitude with Intel Iris Xe graphics, backlit keyboard, and a strong port selection—ideal for business travel and productivity.",
    highlights: [
      "Intel Core i5 vPro (11th Gen)",
      "16GB RAM",
      "256GB SSD storage",
      "Intel Iris Xe graphics",
      "Backlit keyboard",
      "13.3-inch display",
    ],
    specs: [
      { label: "Condition", value: "Brand new (open box)" },
      { label: "Processor", value: "Intel Core i5 vPro (11th Gen)" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Graphics", value: "Intel Iris Xe" },
      { label: "Display", value: '13.3"' },
      { label: "Keyboard", value: "Backlit" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "2× USB‑C, HDMI, 2× USB, SD card" },
      { label: "Camera", value: "HD webcam" },
      { label: "OS", value: "Windows 11 Pro compatible" },
      { label: "Included", value: "Original charger" },
    ],
    images: [{ src: "/products/laptop-dell-latitude.png", alt: "Dell Latitude 7320" }],
  },
  {
    id: "p_lenovo_t460_i7_6th_16_512",
    slug: "lenovo-thinkpad-t460-i7-6th-16gb-512gb",
    name: "Lenovo ThinkPad T460 (i7 6th Gen, 16GB, 512GB SSD)",
    category: "Laptops",
    brand: "Lenovo",
    priceGhs: 4000,
    rating: 4.6,
    inStock: true,
    shortDescription:
      "Upgraded ThinkPad T460 with i7 performance, double battery, and 180° hinge flexibility.",
    description:
      "A strong-value ThinkPad with extra RAM and storage for smoother multitasking. Great for business users who want durability and practical ports.",
    highlights: [
      "Intel Core i7 (6th Gen, 4 CPUs)",
      "16GB RAM",
      "512GB SSD storage",
      "14-inch display",
      "Double battery",
      "Fingerprint + backlit keyboard",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i7 (6th Gen, 4 CPUs)" },
      { label: "Speed", value: "Base 2.8GHz" },
      { label: "Memory", value: "16GB RAM" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: "14-inch" },
      { label: "Form factor", value: "180° hinge / convertible" },
      { label: "Security", value: "Fingerprint" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Battery", value: "Double battery" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "USB, HDMI, Ethernet" },
      { label: "Camera", value: "Webcam" },
    ],
    images: [{ src: "/products/laptop-lenovo-t460.png", alt: "Lenovo ThinkPad T460" }],
  },
  {
    id: "p_hp_x360_i5_8th_8_512_touch_13",
    slug: "hp-x360-i5-8th-8gb-512gb-touch-13inch",
    name: "HP x360 (i5 8th Gen, 8GB, 512GB SSD, Touch)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 7300,
    rating: 4.7,
    inStock: true,
    shortDescription:
      "Neat like-new x360 convertible with touchscreen, Face ID, and fingerprint security.",
    description:
      "A premium HP x360 convertible with a sharp 13-inch FHD display and strong battery life. Great for note-taking, presentations, and flexible everyday work.",
    highlights: [
      "Intel Core i5 (8th Gen)",
      "8GB RAM",
      "512GB SSD storage",
      "13-inch FHD (1080) touchscreen",
      "x360 convertible",
      "Face ID + fingerprint",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (8th Gen)" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "512GB SSD" },
      { label: "Display", value: '13" FHD 1080' },
      { label: "Touch", value: "Yes" },
      { label: "Form factor", value: "x360 convertible" },
      { label: "Security", value: "Fingerprint scanner, Face ID" },
      { label: "Keyboard", value: "Backlit" },
      { label: "Ports", value: "USB + USB‑C" },
      { label: "Battery", value: "Strong battery" },
    ],
    images: [{ src: "/products/laptop-hp-360.png", alt: "HP x360" }],
  },
  {
    id: "p_hp_745g3g4_a10_a12_8_500hdd_256ssd",
    slug: "hp-745-g3-g4-a10-a12-8gb-500hdd-256ssd",
    name: "HP 745 G3/G4 (A10/A12, 8GB, 500GB HDD + 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 3800,
    rating: 4.4,
    inStock: true,
    shortDescription:
      "Slim silver HP laptop with dual storage (HDD + SSD) for speed and space.",
    description:
      "A practical option if you want both fast SSD boot and extra space for files. Good for everyday tasks, school work, and office use.",
    highlights: [
      "AMD A10/A12 (same price)",
      "8GB RAM",
      "500GB HDD + 256GB SSD",
      "Radeon graphics",
      "14.3-inch screen",
      "Camera included",
    ],
    specs: [
      { label: "Model", value: "HP 745 G3/G4" },
      { label: "Processor", value: "AMD A10 / A12" },
      { label: "Speed", value: "Min 1.6GHz · Max 3.0GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "500GB HDD + 256GB SSD" },
      { label: "Display", value: "14.3-inch" },
      { label: "Graphics", value: "Radeon Graphics (512MB dedicated)" },
      { label: "Color", value: "Silver" },
      { label: "Camera", value: "Yes" },
    ],
    images: [{ src: "/products/laptop-hp-840.png", alt: "HP 745" }],
  },
  {
    id: "p_hp_x360_11eeg4_i5_8th_8_256",
    slug: "hp-x360-11eeg4-i5-8th-8gb-256gb",
    name: "HP x360 11EE G4 (i5 8th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 3600,
    rating: 4.5,
    inStock: true,
    shortDescription:
      "Compact 11.6-inch x360 touchscreen laptop—great for portability and everyday use.",
    description:
      "A small, flexible HP x360 with touchscreen. Ideal for students and anyone who wants a lightweight laptop for browsing, documents, and video calls.",
    highlights: [
      "Intel Core i5 (8th Gen)",
      "8GB RAM",
      "256GB SSD storage",
      '11.6" x360 touchscreen',
      "Turbo up to ~3.9GHz",
      "Full silver finish",
    ],
    specs: [
      { label: "Model", value: "HP X360 11EE G4" },
      { label: "Processor", value: "Intel Core i5 (8th Gen)" },
      { label: "Speed", value: "Turbo up to 3.9GHz · Base ~1.61GHz" },
      { label: "Memory", value: "8GB RAM" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '11.6" x360 touch' },
      { label: "Color", value: "Full silver" },
      { label: "Camera", value: "Yes" },
    ],
    images: [{ src: "/products/laptop-hp-360.png", alt: "HP x360 11EE G4" }],
  },
  {
    id: "p_hp_840_g3_i5_6th_8_256",
    slug: "hp-elitebook-840-g3-i5-6th-8gb-256gb",
    name: "HP EliteBook 840 G3 (i5 6th Gen, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 3650,
    rating: 4.5,
    inStock: true,
    shortDescription:
      "Affordable, neat EliteBook with strong battery health and essential ports for work and school.",
    description:
      "A solid business-class laptop at a great price. Good for office apps, browsing, online classes, and video calls—with practical ports and a clean build.",
    highlights: [
      "Intel Core i5 (6th Gen @ 2.6GHz)",
      "8GB RAM",
      "256GB SSD storage",
      "14-inch display",
      "Backlit keyboard + fingerprint",
      "USB‑C + HDMI",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i5 (6th Gen @ 2.6GHz)" },
      { label: "Memory", value: "8GB DDR4" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '14"' },
      { label: "Keyboard", value: "Backlit" },
      { label: "Security", value: "Fingerprint scanner" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Ports", value: "USB‑C, HDMI" },
      { label: "Camera", value: "Webcam" },
      { label: "Battery", value: "Excellent health (per listing)" },
    ],
    images: [{ src: "/products/laptop-hp-840.png", alt: "HP EliteBook 840 G3" }],
  },
  {
    id: "p_hp_1030_g7_x360_i7_10th_16_256_sim",
    slug: "hp-elitebook-x360-1030-g7-i7-10th-16gb-256gb-sim",
    name: "HP EliteBook x360 1030 G7 (i7 10th Gen, 16GB, 256GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 6700,
    rating: 4.8,
    inStock: true,
    shortDescription:
      "Executive x360 touchscreen laptop with SIM slot, premium audio, and strong battery life.",
    description:
      "A premium EliteBook x360 built for executives and power users. Great for travel and meetings with long battery life, touchscreen flexibility, and modern connectivity.",
    highlights: [
      "Intel Core i7 (10th Gen, 6 cores / 12 CPUs)",
      "16GB RAM",
      "256GB SSD storage",
      '13.3" FHD touch IPS',
      "x360 convertible + backlit keyboard",
      "SIM slot + Thunderbolt (USB‑C)",
    ],
    specs: [
      { label: "Processor", value: "Intel Core i7 (10th Gen)" },
      { label: "Speed", value: "Base 1.10GHz · Up to 4.70GHz (Turbo Boost)" },
      { label: "Cores / Threads", value: "6 cores · 12 CPUs" },
      { label: "Memory", value: "16GB DDR4" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: '13.3" FHD touch, IPS, anti-glare (1920×1080)' },
      { label: "Form factor", value: "x360 convertible" },
      { label: "Security", value: "Facial recognition sensor, fingerprint scanner" },
      { label: "Graphics", value: "Intel Ultra HD Premium Graphics" },
      { label: "Ports", value: "2× USB‑C (Thunderbolt), 2× USB 3.1, HDMI" },
      { label: "Connectivity", value: "Wi‑Fi, Bluetooth" },
      { label: "Audio", value: "Bang & Olufsen speakers" },
      { label: "Camera", value: "1080p HD camera" },
      { label: "Extras", value: "Active SIM slot for internet" },
      { label: "Included", value: "Original charger" },
      { label: "Battery", value: "Very strong (listing: 12+ hours)" },
    ],
    images: [{ src: "/products/laptop-hp-360.png", alt: "HP EliteBook x360 1030 G7" }],
  },
  {
    id: "p_hp_840g8",
    slug: "hp-elitebook-840-g8",
    name: "HP EliteBook 840 G8 (i7, 16GB, 512GB SSD)",
    category: "Laptops",
    brand: "HP",
    priceGhs: 12999,
    rating: 4.7,
    inStock: true,
    shortDescription: "Premium business laptop built for performance and portability.",
    description:
      "A powerful, sleek business laptop for professionals. Ideal for work, school, and everyday productivity with fast SSD storage and reliable build quality.",
    highlights: ["Intel Core i7", "16GB RAM", "512GB NVMe SSD", "14-inch FHD display"],
    specs: [
      { label: "Processor", value: "Intel Core i7 (11th Gen)" },
      { label: "Memory", value: "16GB DDR4" },
      { label: "Storage", value: "512GB NVMe SSD" },
      { label: "Display", value: "14-inch FHD (1920×1080)" },
      { label: "OS", value: "Windows 11 Pro" },
    ],
    images: [
      { src: "/products/laptop-hp-840.png", alt: "HP EliteBook 840 G8" },
      { src: "/products/laptop-hp-360.png", alt: "HP EliteBook x360" },
    ],
  },
  {
    id: "p_dell_7420",
    slug: "dell-latitude-7420",
    name: "Dell Latitude 7420 (i5, 8GB, 256GB SSD)",
    category: "Laptops",
    brand: "Dell",
    priceGhs: 8999,
    rating: 4.5,
    inStock: true,
    shortDescription: "Reliable, lightweight laptop for work and travel.",
    description:
      "A dependable Latitude with a clean design and great battery life. Perfect for students and office productivity with smooth everyday performance.",
    highlights: ["Intel Core i5", "8GB RAM", "256GB SSD", "Wi‑Fi 6"],
    specs: [
      { label: "Processor", value: "Intel Core i5 (11th Gen)" },
      { label: "Memory", value: "8GB DDR4" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Connectivity", value: "Wi‑Fi 6, Bluetooth" },
      { label: "Ports", value: "USB‑C, USB‑A, HDMI" },
    ],
    images: [
      { src: "/products/laptop-dell-latitude.png", alt: "Dell Latitude 7420" },
      { src: "/products/laptop-dell-5440.png", alt: "Dell Latitude" },
    ],
  },
  {
    id: "p_lenovo_t14",
    slug: "lenovo-thinkpad-t14",
    name: "Lenovo ThinkPad T14 (Ryzen 7, 16GB, 512GB SSD)",
    category: "Laptops",
    brand: "Lenovo",
    priceGhs: 11999,
    rating: 4.8,
    inStock: true,
    shortDescription: "Legendary ThinkPad durability with modern performance.",
    description:
      "The ThinkPad T-series is built for serious work. Rugged reliability, excellent keyboard comfort, and snappy performance for demanding tasks.",
    highlights: ["AMD Ryzen 7", "16GB RAM", "512GB SSD", "Backlit keyboard"],
    specs: [
      { label: "Processor", value: "AMD Ryzen 7" },
      { label: "Memory", value: "16GB DDR4" },
      { label: "Storage", value: "512GB NVMe SSD" },
      { label: "Security", value: "Fingerprint reader" },
      { label: "Build", value: "Military-grade durability" },
    ],
    images: [
      { src: "/products/laptop-lenovo-t14.png", alt: "Lenovo ThinkPad T14" },
      { src: "/products/laptop-lenovo-t460.png", alt: "Lenovo ThinkPad" },
    ],
  },
  {
    id: "p_macbook_air_m2",
    slug: "apple-macbook-air-m2",
    name: "Apple MacBook Air (M2, 8GB, 256GB)",
    category: "Laptops",
    brand: "Apple",
    priceGhs: 16999,
    rating: 4.9,
    inStock: true,
    shortDescription: "Ultra-thin, silent, and incredibly fast with Apple silicon.",
    description:
      "A premium everyday machine with exceptional efficiency and a gorgeous display. Ideal for creative work, study, and professional productivity.",
    highlights: ["Apple M2", "Retina display", "All-day battery", "Fanless design"],
    specs: [
      { label: "Chip", value: "Apple M2" },
      { label: "Memory", value: "8GB unified memory" },
      { label: "Storage", value: "256GB SSD" },
      { label: "Display", value: "13.6-inch Liquid Retina" },
      { label: "Battery", value: "Up to 18 hours" },
    ],
    images: [
      { src: "/products/mac-1.svg", alt: "Apple MacBook Air" },
      { src: "/products/mac-2.svg", alt: "Apple MacBook Air angled" },
    ],
  },
  {
    id: "p_tplink_ax53",
    slug: "tp-link-archer-ax53-wifi6-router",
    name: "TP-Link Archer AX53 Wi‑Fi 6 Router",
    category: "Networking",
    brand: "TP-Link",
    priceGhs: 899,
    rating: 4.6,
    inStock: true,
    shortDescription: "Fast, stable Wi‑Fi 6 for homes and small offices.",
    description:
      "Upgrade your network with Wi‑Fi 6 speed and better coverage. Great for streaming, video calls, and multiple device households.",
    highlights: ["Wi‑Fi 6", "Dual-band", "MU‑MIMO", "Beamforming"],
    specs: [
      { label: "Standard", value: "Wi‑Fi 6 (802.11ax)" },
      { label: "Bands", value: "Dual-band 2.4GHz + 5GHz" },
      { label: "Coverage", value: "Beamforming + high-gain antennas" },
      { label: "Security", value: "WPA3" },
    ],
    images: [
      {
        src: "/products/router-1.svg",
        alt: "Networking router",
      },
      {
        src: "/products/router-2.svg",
        alt: "Wi‑Fi device close-up",
      },
    ],
  },
  {
    id: "p_switch_8port",
    slug: "gigabit-switch-8-port",
    name: "8‑Port Gigabit Ethernet Switch",
    category: "Networking",
    brand: "TP-Link",
    priceGhs: 249,
    rating: 4.4,
    inStock: true,
    shortDescription: "Plug-and-play switching for fast wired networks.",
    description:
      "A compact switch for expanding your wired network in the office or at home. Ideal for CCTV, desktops, and routers.",
    highlights: ["8× Gigabit ports", "Fanless", "Metal housing", "Energy efficient"],
    specs: [
      { label: "Ports", value: "8× RJ45 Gigabit" },
      { label: "Design", value: "Fanless, silent" },
      { label: "Setup", value: "Unmanaged (plug & play)" },
      { label: "Housing", value: "Metal" },
    ],
    images: [
      {
        src: "/products/p6-1.jpg",
        alt: "Ethernet and networking equipment",
      },
      {
        src: "/products/p6-2.jpg",
        alt: "Networking cables and hardware",
      },
    ],
  },
  {
    id: "p_mouse_wireless",
    slug: "wireless-mouse-silent",
    name: "Wireless Silent Mouse",
    category: "Accessories",
    brand: "Dell",
    priceGhs: 149,
    rating: 4.3,
    inStock: true,
    shortDescription: "Comfortable, quiet clicks for office productivity.",
    description:
      "A simple, reliable mouse with silent clicks and smooth tracking. Great for workspaces and study environments.",
    highlights: ["Silent clicks", "2.4GHz wireless", "Long battery life"],
    specs: [
      { label: "Connection", value: "2.4GHz USB receiver" },
      { label: "Buttons", value: "3" },
      { label: "Noise", value: "Silent click" },
    ],
    images: [
      {
        src: "/products/p7-1.jpg",
        alt: "Computer mouse and accessories",
      },
      {
        src: "/products/p7-2.jpg",
        alt: "Desk accessories close-up",
      },
    ],
  },
  {
    id: "p_ssd_1tb",
    slug: "portable-ssd-1tb",
    name: "Portable SSD 1TB (USB‑C)",
    category: "Storage",
    brand: "ASUS",
    priceGhs: 699,
    rating: 4.5,
    inStock: true,
    shortDescription: "High-speed storage for backups and creative workflows.",
    description:
      "Fast transfers and compact portability. Ideal for photographers, editors, students, and anyone who needs reliable extra storage.",
    highlights: ["1TB", "USB‑C", "High speed", "Compact"],
    specs: [
      { label: "Capacity", value: "1TB" },
      { label: "Interface", value: "USB‑C" },
      { label: "Use case", value: "Backups, media, work files" },
    ],
    images: [
      {
        src: "/products/p8-1.jpg",
        alt: "Portable SSD storage",
      },
      {
        src: "/products/p8-2.jpg",
        alt: "External storage with cable",
      },
    ],
  },
];

export function getProductBySlug(slug: string) {
  return products.find((p) => p.slug === slug) ?? null;
}

